import React from "react";
import {
    BarLoader,
    BeatLoader,
    BounceLoader,
    CircleLoader,
    ClimbingBoxLoader,
    ClipLoader,
    ClockLoader,
    DotLoader,
    FadeLoader,
    GridLoader,
    HashLoader,
    MoonLoader,
    PacmanLoader,
    PropagateLoader,
    PuffLoader,
    PulseLoader,
    RingLoader,
    RiseLoader,
    RotateLoader,
    ScaleLoader,
    SkewLoader,
    SquareLoader,
    SyncLoader,
} from "react-spinners";

import {
    BallSpinner,
    BarsSpinner,
    CircleSpinner,
    CubeSpinner,
    DominoSpinner,
    FillSpinner,
    FireworkSpinner,
    FlagSpinner,
    GridSpinner,
    GuardSpinner,
    HeartSpinner,
    ImpulseSpinner,
    PulseSpinner,
    PushSpinner,
    SequenceSpinner,
    SphereSpinner,
    SpiralSpinner,
    StageSpinner,
    SwapSpinner,
    WaveSpinner,
    ClapSpinner,
    RotateSpinner,
    SwishSpinner,
    GooSpinner,
    CombSpinner,
    PongSpinner,
    RainbowSpinner,
    RingSpinner,
    HoopSpinner,
    FlapperSpinner,
    MagicSpinner,
    JellyfishSpinner,
    TraceSpinner,
    ClassicSpinner,
    MetroSpinner,
    WhisperSpinner,
} from "react-spinners-kit";

import { SpinnerSection } from "./SpinnerElements";

const Spinner = ({loading, key}) => {
    const spinnersList = [
        <BallSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <BarsSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <CircleSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <CubeSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <DominoSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <FillSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <FireworkSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <FlagSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <GridSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <GuardSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <HeartSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <ImpulseSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <PulseSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <PushSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <SequenceSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <SphereSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <SpiralSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <StageSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <SwapSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <WaveSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <ClapSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <RotateSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <SwishSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <GooSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <CombSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <PongSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <RainbowSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <RingSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <HoopSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <FlapperSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <MagicSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <JellyfishSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <TraceSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <ClassicSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <MetroSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,
        <WhisperSpinner color={"#20c20e"} SIZE={30} loading={loading} key={key} />,

        <BarLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <BeatLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
        <BounceLoader color={"#20c20e"} loading={loading} size={60} key={key} />,
        <CircleLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <ClimbingBoxLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
        <ClipLoader color={"#20c20e"} loading={loading} size={35} key={key} />,
        <ClockLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <DotLoader color={"#20c20e"} loading={loading} size={60} key={key} />,
        <FadeLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <GridLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
        <HashLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <MoonLoader color={"#20c20e"} loading={loading} size={60} key={key} />,
        <PacmanLoader color={"#20c20e"} loading={loading} size={25} key={key} />,
        <PropagateLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
        <PuffLoader color={"#20c20e"} loading={loading} size={60} key={key} />,
        <PulseLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
        <RingLoader color={"#20c20e"} loading={loading} size={60} key={key} />,
        <RiseLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
        <RotateLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
        <ScaleLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <SkewLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <SquareLoader color={"#20c20e"} loading={loading} size={50} key={key} />,
        <SyncLoader color={"#20c20e"} loading={loading} size={15} key={key} />,
    ];

    let loadingSpinner = spinnersList[Math.floor(Math.random() * spinnersList.length)];

    return (
        <div>
            <SpinnerSection>{loadingSpinner}</SpinnerSection>
        </div>
    );
};

export default Spinner;
