const InternshipProgramData = [
    {
        id: 1,
        cycleName: "Jan - Feb Internship",
        applicationOpen: "Nov 1",
        applicationClose: "Nov 30",
        applicationOpenDate: "2023-11-01T00:00:00.000Z",
        applicationCloseDate: "2023-12-01T00:00:00.000Z",
        internshipStartTime: "2024-01-01T00:00:00.000Z",
        interviewDate: "Dec",
        internshipPeriod: "Jan to Feb",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
    {
        id: 2,
        cycleName: "April - May Internship",
        applicationOpen: "Feb 1",
        applicationClose: "Feb 29",
        applicationOpenDate: "2024-02-01T00:00:00.000Z",
        applicationCloseDate: "2024-03-01T00:00:00.000Z",
        internshipStartTime: "2024-04-01T00:00:00.000Z",
        interviewDate: "March",
        internshipPeriod: "April to May",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
    {
        id: 3,
        cycleName: "July - Aug Internship",
        applicationOpen: "May 1",
        applicationClose: "May 31",
        applicationOpenDate: "2024-05-01T00:00:00.000Z",
        applicationCloseDate: "2024-06-01T00:00:00.000Z",
        internshipStartTime: "2024-07-01T00:00:00.000Z",
        interviewDate: "June",
        internshipPeriod: "July to Aug",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
    {
        id: 4,
        cycleName: "Sep - Nov Internship",
        applicationOpen: "Sep 6",
        applicationClose: "Sep 13",
        applicationOpenDate: "2024-09-06T00:00:00.000Z",
        applicationCloseDate: "2024-09-13T00:00:00.000Z",
        internshipStartTime: "2024-09-14T00:00:00.000Z",
        interviewDate: "Interview === 1st two weeks of Performance",
        internshipPeriod: "Sep to Nov",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
];

export default InternshipProgramData;
