export const CyberSecCoursesData = [
    {
        id: "freeYoutubeCourses",
        sectionsHeading: "Penetration Testing courses",
        topLine: 'Free Courses',
        YTChannelImageLink: "https://i.ytimg.com/vi/qJ9ZmkMvkcA/maxresdefault.jpg",
        tag: 'Cyber Security',
        videoHeading: ' Penetration Testing Bootcamp - Introduction',
        videoDescription: "In this video, I explore the various cybersecurity paths available as well as their corresponding certifications and skills required in order to transition into a cybersecurity role/career.",
        videoLink: "https://www.youtube.com/watch?v=qJ9ZmkMvkcA&list=PLBf0hzazHTGOepimcP15eS6Y-aR4m6ql3",
        channelName: "HackerSploit",
        channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu9nSdhYbPUgxIavX6vicAOFioLHhkuCNeHcp-Icpw=s48-c-k-c0x00ffffff-no-rj",
        timeStamp: "Oct 7 2022",
        alt: 'Red Team Courses',
        channelLink: "https://www.youtube.com/c/HackerSploit",
    },
    {
        id: "freeYoutubeCourses",
        sectionsHeading: "Penetration Testing courses",
        topLine: 'Free Courses',
        YTChannelImageLink: "https://i.ytimg.com/vi/fNzpcB7ODxQ/maxresdefault.jpg",
        tag: 'Cyber Security',
        videoHeading: 'Ethical Hacking in 12 Hours - Full Course - Learn to Hack!',
        videoDescription: "In this video, I explore the various cybersecurity paths available as well as their corresponding certifications and skills required in order to transition into a cybersecurity role/career.",
        videoLink: "https://youtu.be/fNzpcB7ODxQ",
        channelName: "The Cyber Mentor",
        channelLogo: "https://yt3.ggpht.com/ytc/AKedOLRGnc0be-YXi3zenYi6s8uwgPxi_IrLBZ7Rigv7=s48-c-k-c0x00ffffff-no-rj",
        timeStamp: "Oct 7 2022",
        alt: 'ResourcesSvg',
        channelLink: "https://www.youtube.com/c/TheCyberMentor",
    }
];
