export {default as Navbar} from './Navbar/Navbar'
export {default as Hero} from './Hero'
export {default as Services} from './Services'
export {default as Loader} from './Loader'
export {default as Footer} from './Footer'