export {default as Navbar} from './Navbar/Navbar'
export {default as Sidebar} from './Navbar/Sidebar/Sidebar'
export {default as Hero} from './Hero/Hero'
export {default as Info} from './Info/Info'
export {default as Services} from './Services/Services'
export {default as Contribute} from './Contribute/Contribute'
export {default as Footer} from './Footer/Footer'
export {default as ComingSoon} from './ComingSoon'