const InternshipProgramData = [
    {
        id: 1,
        cycleName: "Jan - Feb Internship",
        applicationOpen: "Nov 1",
        applicationClose: "Dec 20",
        applicationOpenDate: "2022-11-01T00:00:00.000Z",
        applicationCloseDate: "2022-12-21T00:00:00.000Z",
        internshipStartTime: "2023-01-01T00:00:00.000Z",
        interviewDate: "Dec",
        internshipPeriod: "Jan to Feb",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
    {
        id: 2,
        cycleName: "April - May Internship",
        applicationOpen: "Feb 1",
        applicationClose: "March 20",
        applicationOpenDate: "2023-02-01T00:00:00.000Z",
        applicationCloseDate: "2023-03-21T00:00:00.000Z",
        internshipStartTime: "2023-04-01T00:00:00.000Z",
        interviewDate: "March",
        internshipPeriod: "April to May",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
    {
        id: 3,
        cycleName: "July - Aug Internship",
        applicationOpen: "May 1",
        applicationClose: "June 20",
        applicationOpenDate: "2023-05-01T00:00:00.000Z",
        applicationCloseDate: "2023-06-21T00:00:00.000Z",
        internshipStartTime: "2023-07-01T00:00:00.000Z",
        interviewDate: "June",
        internshipPeriod: "July to Aug",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
    {
        id: 4,
        cycleName: "Oct - Nov Internship",
        applicationOpen: "Aug 1",
        applicationClose: "Sep 20",
        applicationOpenDate: "2023-08-01T00:00:00.000Z",
        applicationCloseDate: "2023-09-21T00:00:00.000Z",
        internshipStartTime: "2023-10-01T00:00:00.000Z",
        interviewDate: "Sep",
        internshipPeriod: "Oct to Nov",
        roles: "Description of internship roles and responsibilities",
        eligibility: "Eligibility requirements",
        applicationProcedure: "Application procedures",
    },
];

export default InternshipProgramData;
